permalink: /:year/:month/:day/:title.html
paginate: 10
# this should be update to Maruku asap
markdown: redcarpet

# 作者信息
author: 
  name: Aruforce
  email: Aruforce@163.com
  github: https://github.com/Aruforce  
# 站点信息
title: Arufroce的NoteBook
description: Aruforce的笔记本
url: https://www.aruforce.site
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/img/avantar.jpg
favicon: /public/img/avantar.jpg

# disqus 设置
disqus:
  shortname: Aruforce

# 主题设置，自动激活某个标签
active: 技术

# 首页除了最新文章外显示分类
cates: 
  - Optimization
  - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档